"""Seuils de décision centralisés et auditables."""

FOOTBALL_VALIDATED_MIN_EXPECTED_ROI = 0.05
FOOTBALL_OPPORTUNITY_MIN_EXPECTED_ROI = 0.0

FOOTBALL_VALIDATED_PAPER_STAKE = 1.0
FOOTBALL_OPPORTUNITY_PAPER_STAKE = 0.5
